// <auto-generated />
using System;
using InternTask.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternTask.Migrations
{
    [DbContext(typeof(ScoringDbContext))]
    [Migration("20250526064234_SeedConditionConfigs")]
    partial class SeedConditionConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternTask.Entities.ConditionConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConditionConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = true,
                            ParametersJson = "{\"MinimumSalary\":\"5000\",\"SalaryMultiplier\":\"1.2\"}",
                            Priority = 1,
                            Required = true,
                            Type = "SalaryThreshold"
                        },
                        new
                        {
                            Id = 2,
                            Enabled = true,
                            ParametersJson = "{\"MaxLoanCount\":\"5\"}",
                            Priority = 2,
                            Required = true,
                            Type = "LoanCountLimit"
                        },
                        new
                        {
                            Id = 3,
                            Enabled = true,
                            ParametersJson = "{\"MinimumBalance\":\"1000\",\"BalanceMultiplier\":\"2.0\"}",
                            Priority = 3,
                            Required = false,
                            Type = "AccountBalance"
                        },
                        new
                        {
                            Id = 4,
                            Enabled = false,
                            ParametersJson = "{\"FailIfHasDefault\":\"true\"}",
                            Priority = 4,
                            Required = true,
                            Type = "DefaultHistory"
                        });
                });

            modelBuilder.Entity("InternTask.Entities.ConditionEvaluationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("EligibleAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("ScoringResultEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScoringResultEntityId");

                    b.ToTable("ConditionEvaluations");
                });

            modelBuilder.Entity("InternTask.Entities.ScoringResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EligibleAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScoringResults");
                });

            modelBuilder.Entity("InternTask.Entities.ConditionEvaluationEntity", b =>
                {
                    b.HasOne("InternTask.Entities.ScoringResultEntity", "ScoringResult")
                        .WithMany("ConditionEvaluations")
                        .HasForeignKey("ScoringResultEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringResult");
                });

            modelBuilder.Entity("InternTask.Entities.ScoringResultEntity", b =>
                {
                    b.Navigation("ConditionEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
